//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.17.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Show</summary>
	[PublishedModel("show")]
	public partial class Show : PublishedContentModel, IShowControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		public new const string ModelTypeAlias = "show";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Show, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Show(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// City: Enter the city of the show
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		[ImplementPropertyType("city")]
		public virtual string City => global::Umbraco.Web.PublishedModels.ShowControls.GetCity(this);

		///<summary>
		/// Country: Enter the country code (for exampe: NL)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		[ImplementPropertyType("country")]
		public virtual string Country => global::Umbraco.Web.PublishedModels.ShowControls.GetCountry(this);

		///<summary>
		/// Date: Select the date of the show
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		[ImplementPropertyType("date")]
		public virtual global::System.DateTime Date => global::Umbraco.Web.PublishedModels.ShowControls.GetDate(this);

		///<summary>
		/// Notes: Enter the name of the festival
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		[ImplementPropertyType("notes")]
		public virtual string Notes => global::Umbraco.Web.PublishedModels.ShowControls.GetNotes(this);

		///<summary>
		/// Show link: Enter the link to the venue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		[ImplementPropertyType("showLink")]
		public virtual global::Umbraco.Web.Models.Link ShowLink => global::Umbraco.Web.PublishedModels.ShowControls.GetShowLink(this);

		///<summary>
		/// Venue or festival name: Enter the name of the venue
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		[ImplementPropertyType("showName")]
		public virtual string ShowName => global::Umbraco.Web.PublishedModels.ShowControls.GetShowName(this);

		///<summary>
		/// Tickets link: Enter the link to the tickets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.2")]
		[ImplementPropertyType("ticketsLink")]
		public virtual global::Umbraco.Web.Models.Link TicketsLink => global::Umbraco.Web.PublishedModels.ShowControls.GetTicketsLink(this);
	}
}
